// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ8tZ_MvzjrPfZVzqswngEC0Id7wd4NTA',
    appId: '1:922475183780:web:7caebc5f0bcd5bbeb0f031',
    messagingSenderId: '922475183780',
    projectId: 'avss-61f2b',
    authDomain: 'avss-61f2b.firebaseapp.com',
    storageBucket: 'avss-61f2b.firebasestorage.app',
    measurementId: 'G-DTED4WXY1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnaAysInzJ0SFZuCp1pwAiSd9AfsOF_9Q',
    appId: '1:922475183780:android:e8e32d687d945623b0f031',
    messagingSenderId: '922475183780',
    projectId: 'avss-61f2b',
    storageBucket: 'avss-61f2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOhLjGdXG2LcsBeRVyRlIv3e9ZNgLu5-s',
    appId: '1:922475183780:ios:900e2ce0a6e87858b0f031',
    messagingSenderId: '922475183780',
    projectId: 'avss-61f2b',
    storageBucket: 'avss-61f2b.firebasestorage.app',
    iosBundleId: 'com.example.avsSaver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOhLjGdXG2LcsBeRVyRlIv3e9ZNgLu5-s',
    appId: '1:922475183780:ios:900e2ce0a6e87858b0f031',
    messagingSenderId: '922475183780',
    projectId: 'avss-61f2b',
    storageBucket: 'avss-61f2b.firebasestorage.app',
    iosBundleId: 'com.example.avsSaver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ8tZ_MvzjrPfZVzqswngEC0Id7wd4NTA',
    appId: '1:922475183780:web:11ee2d5e1409dd93b0f031',
    messagingSenderId: '922475183780',
    projectId: 'avss-61f2b',
    authDomain: 'avss-61f2b.firebaseapp.com',
    storageBucket: 'avss-61f2b.firebasestorage.app',
    measurementId: 'G-2YWJ0HEW2C',
  );
}
